Add a plugin to create virtual projects from the patterns project
WordPress/wordpress.org pull request #108
Opened 2022-11-03 11:08 UTC by amieiro

When a translator translates the patterns, all the strings are under the same project, so she can't focus in translating one pattern easily.

![image](https://user-images.githubusercontent.com/1667814/199703839-3f462438-15c4-4fe4-a6ef-f12fa6aee812.png)

This PR creates "virtual projects" for the patterns, so each pattern has its own project. This approach try to improve the individual translation for patterns.

![image](https://user-images.githubusercontent.com/1667814/199704460-802fa57a-57fa-478f-860c-092ab619a11c.png)

All the original strings are under the same project (project_id 473698) and the `references` field has the different URLs (patterns) in which the string in present.

This approach has some limitations:
- The virtual projects are alphabetically ordered.
- The search and the filter are not working.

2022-11-23 09:07 UTC, akirk requested changes
Nice. Just the URLs of the projects were broken, I suggested the changes necessary to make it work.

![virtual-projects](https://user-images.githubusercontent.com/203408/203507742-2cbdc038-7f1c-4fdf-913a-c0d14d1c9145.gif)

2022-11-23 09:07 UTC, akirk commented on wordpress.org/public_html/wp-content/plugins/wporg-gp-virtual-projects/wporg-gp-virtual-projects.php
> +			$subproject->path                = 'patterns/' . $subproject->slug;
This leads to a 404. The idea was to directly link to a reference search like this:
```suggestion
			$subproject->path                = '/../../../projects/patterns/core/' . $locale_slug . '/' . $set_slug. '/?filters[term_scope]=scope_references&filters[term]=' . urlencode(    $url ) . '&';
```

2022-11-23 09:07 UTC, akirk commented on wordpress.org/public_html/wp-content/plugins/wporg-gp-virtual-projects/wporg-gp-virtual-projects.php
> +		add_filter( 'gp_subprojects', array( $this, 'add_virtual_projects' ), 10, 1 );
```suggestion
		add_filter( 'gp_subprojects', array( $this, 'add_virtual_projects' ), 10, 3 );
```

2022-11-23 09:07 UTC, akirk commented on wordpress.org/public_html/wp-content/plugins/wporg-gp-virtual-projects/wporg-gp-virtual-projects.php
> +	public function add_virtual_projects( $data ) {
```suggestion
	public function add_virtual_projects( $data, $locale_slug, $set_slug ) {
```

2022-11-23 09:07 UTC, akirk commented on wordpress.org/public_html/wp-content/plugins/wporg-gp-routes/inc/routes/class-locale.php
> +		$data                           = apply_filters( 'gp_subprojects', $data );
```suggestion
		$data                           = apply_filters( 'gp_subprojects', $data, $locale_slug, $set_slug );
```

2022-11-23 09:28 UTC, dd32 commented
Is there any reason why we shouldn't just create real sub-projects?

The decision to not create sub-projects for each pattern was made when it was assumed we'd not have as many strings as we've ended up with, and/or that it'd be short-lived (ie. We'd end up having translations done within the Pattern Creator, rather than being done externally)

2022-11-23 09:42 UTC, akirk commented
We thought it would be useful to keep them all in the same project because of re-used strings resp. strings used in multiple patterns. Some patterns are just slight variations of others with some additional or replaced strings. It's quite useful to automatically be able to reuse those strings.

2022-11-23 10:56 UTC, akirk commented
Overall I think it's worth having this as a first step and we'll research if we can change it to do it with multiple projects.

It will need changes to how the patterns are imported to GlotPress (which I don't know how it's done) and to how translations are loaded.

2022-11-24 02:27 UTC, dd32 commented
Thanks for the context @akirk.

We do have code on translate.w.org already for syncing translations between projects where the source-string remains the same, although that's limited to between plugin stable<->dev at present due to translator issues translating it between different plugins. The context difference between two blocks however seems much smaller, so your current approach seems reasonable.

My suggestion is just to not go down the path too far of attempting to make it work with filtering / subscriptions / favouriting / etc.. syncing between projects is going to be easier in the long-term than reinventing it all for this.

2023-02-16 18:04 UTC, amieiro commented
I have deployed this PR and I have written a [post](https://make.wordpress.org/polyglots/2023/02/16/virtual-projects-for-the-patterns-project/) to inform to the community, so I close this PR. Thank you for the review and feedback.

2023-02-16 18:04 UTC, closed without merging