Add a cache to the suggestions
WordPress/wordpress.org pull request #141
Opened 2023-06-01 10:36 UTC by amieiro

Currently, in the translation environment (translate.w.org), when we translate a project, we have suggestions from our own translation memory (TM), from OpenAI (ChatGPT) and from DeepL. We have the translations from other languages, too.

This PR adds a local cache for the previous suggestions, in 4 variables, so it caches the suggestions and translations from other languages:
- For the first row when the page loads, so when the user opens the first row, she gets the suggestions immediately.
- For the next row, when she opens a row, so when the user opens the next row, she gets the suggestions immediately.

We only cache what we believe to be the most likely row to be opened next, not all of them, as this avoids making excessive API calls, with the consequent economic cost (OpenAI and DeepL).

2023-06-15 10:26 UTC, trymebytes reviewed
I tested and it works as expected. When I jumped from row 1 to say row 5, I found out that it sent 8 AJAX requests, 4 for the row 5 I opened and another for the row 6 I have yet to open. If I decide not to open row 6 and jump to row 8, the same 8 AJAX requests would be made.

I was wondering if we can and need to reduce the occurrence of these multiple requests.

2023-06-15 11:52 UTC, amieiro commented
> I tested and it works as expected. When I jumped from row 1 to say row 5, I found out that it sent 8 AJAX requests, 4 for the row 5 I opened and another for the row 6 I have yet to open. If I decide not to open row 6 and jump to row 8, the same 8 AJAX requests would be made.
> 
> I was wondering if we can and need to reduce the occurrence of these multiple requests.

**This is the expected work**. I only preload the first row when the page is loaded, with the closed table, because I expect the translator will start translating in the first row. And when the translator opens a row, I preload the next one, because I expected the translator will continue translating the next row.

I know the user can jump between alternate rows, and the requests will work fine, but without preloading. I don't want to preload all the rows, because this will consume a lot of API tokens, so I only preload the row that is most likely to be opened.

2023-06-15 12:11 UTC, trymebytes approved these changes

2023-06-22 08:43 UTC, akirk requested changes
I testssd this in Firefox and I do see preloading happening but I run into the following two issues:

1. The tabs are always truncated:
<img width="570" alt="Screenshot 2023-06-22 at 10 37 18" src="https://github.com/WordPress/wordpress.org/assets/203408/5ccf09c0-1d32-416f-aa13-87e75e5573d8">

2. When I naviate to a row while it is preloading, it stays empty:
![tab-not-loading](https://github.com/WordPress/wordpress.org/assets/203408/4d7bc5d3-6d60-45c7-8694-cbd1317fa609)

When I navigate around I can get it to display but not very easily:
![tab-not-loading2](https://github.com/WordPress/wordpress.org/assets/203408/af754bc8-9f4a-417e-98f5-157e2e490fc0)

2023-06-22 08:50 UTC, akirk approved these changes
This works well for me.

2023-06-26 10:05 UTC, amieiro commented
Released [here](https://github.com/WordPress/wordpress.org/commit/95bd5ada1360e9be77712d7f1e2855d80b7fb43c).

2023-06-26 10:05 UTC, closed without merging